name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test_gcc_release:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Build SSVM-EVMC using gcc with Release mode
      run: |
        if ! command ninja; then
          apt update
          apt install -y ninja-build
        fi
        cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_TOOLS=OFF -DSSVM_DISABLE_AOT_RUNTIME=ON .
        cmake --build build

    - name: Test SSVM-EVMC
      run: |
        cd build/test/evmc
        ./ssvmEVMCTest

  build_test_clang_debug:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Build SSVM-EVMC using clang with Debug mode
      run: |
        if ! command ninja; then
          apt update
          apt install -y ninja-build
        fi
        cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_TOOLS=OFF -DSSVM_DISABLE_AOT_RUNTIME=ON .
        cmake --build build

    - name: Test SSVM-EVMC
      run: |
        cd build/test/evmc
        ./ssvmEVMCTest

  build_test_clang_release:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Build SSVM-EVMC using clang with Release mode
      run: |
        if ! command ninja; then
          apt update
          apt install -y ninja-build
        fi
        cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_TOOLS=OFF -DSSVM_DISABLE_AOT_RUNTIME=ON .
        cmake --build build

    - name: Test SSVM-EVMC
      run: |
        cd build/test/evmc
        ./ssvmEVMCTest
