name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test_gcc_release:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Build WASMEDGE-EVMC using gcc with Release mode
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release .
        cmake --build build -- -j4

    - name: Test WASMEDGE-EVMC
      run: |
        cd build/test/evmc
        ./wasmedgeEVMCTest

  build_test_clang_debug:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Build WASMEDGE-EVMC using clang with Debug mode
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug .
        cmake --build build -- -j4

    - name: Test WASMEDGE-EVMC
      run: |
        cd build/test/evmc
        ./wasmedgeEVMCTest

  build_test_clang_release:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Build WASMEDGE-EVMC using clang with Release mode
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release .
        cmake --build build -- -j4

    - name: Test WASMEDGE-EVMC
      run: |
        cd build/test/evmc
        ./wasmedgeEVMCTest
