name: "build without tools and aot"
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug  -DBUILD_TESTS=ON -DBUILD_TOOLS=FALSE -DSSVM_DISABLE_AOT_RUNTIME=ON .. && make -j"
